// **** Environments ****

export const  BASE_URL = "https://getgftd-development.enorness.com/api/v1/user/"


export const APIS = {
    Signup: BASE_URL + "newsignup",
    Login: BASE_URL + 'login',
    Register: BASE_URL + 'signup',
    NewSignup: BASE_URL + "newsignup",
    OTP: BASE_URL + 'otpVerification',
    CheckPhone: BASE_URL + 'checkuser', // check phone api
    completeProfile: BASE_URL + 'completeProfile',
    ForgotPassword: BASE_URL + 'forgetpassword',
    DeleteAccount: BASE_URL + 'deleteAccount',
    addToWishlist: BASE_URL + 'makewishlist',
    GetLists: BASE_URL + 'getList',
    ContactUs: BASE_URL + 'contactus',
    PostFeeds: BASE_URL + 'postFeed',
    RemoveFeed: BASE_URL + 'removefeed',
    GetFeeds: BASE_URL + 'getFeed/0',
    AddItems: BASE_URL + 'addItem',
    UpdateItems: BASE_URL + 'update-item',
    SentGift: BASE_URL + 'sentgift/',
    SendGift: BASE_URL + 'sendgift',
    GetFriendlist: BASE_URL + 'getfriendlist',
    ProfileInfo: BASE_URL + 'profileinfo',
    ChangeNumber: BASE_URL + 'verifyOtpMobileUpdate',
    CheckBankAccount: BASE_URL + 'checkBankAccount',
    AddBankAccount: BASE_URL + 'addAccount',
    BankDetails: BASE_URL + 'bankDetail',
    GetUsersStorelist: BASE_URL + 'getList/2/',
    GetUsersWishlist: BASE_URL + 'getList/4/',
    GetUsersFriendlist: BASE_URL + 'getList/5/',
    GetUsersItems: BASE_URL + 'getList/6/',
    AddFriend: BASE_URL + 'registerfriend',
    RemoveFriend: BASE_URL + 'removefriend',
    Sorting: BASE_URL + 'filter',
    DeleteBankDetails: BASE_URL + 'deletebankDetail/',
    GetAllNotifications: BASE_URL + 'notificationListing',
    NotificationReply: BASE_URL + 'notificationReply',
    UserSetting: BASE_URL + 'settings',
    ShowBankDetails: BASE_URL + 'showbankDetail',
    Plaidlinktoken: BASE_URL + 'plaidlinktoken',
    GetWallet: BASE_URL + 'getwalletbalance',
    RedeemSila: BASE_URL + 'redeemsila',
    DocKYC: BASE_URL + 'doc_kyc',
    LikeNotification: BASE_URL + 'likenotification',
    GetEmojis: BASE_URL + 'getemojis',
    GetProfileImage: BASE_URL + 'getprofileimage',
    ProfileInfo: BASE_URL + 'profileinfo',
    GetAllGftdUsers: BASE_URL + 'getAllUsers',
    CheckToken: BASE_URL + 'check-token',
    DefaultBank: BASE_URL + 'makedefaultbank',
    UploadKYCDoc: BASE_URL + 'upload_kyc_document',
    CreateWishlists: BASE_URL + 'createwishlist',
    EditWishlists: BASE_URL + 'editwishlist',
    DeleteWishlists: BASE_URL + 'deletewishlist',
    ShowWishlists: BASE_URL + 'showwishlist',
    GetWishlistsByUserId: BASE_URL + 'getuserwishlist/',
    GetWishlistsByUserIdWishId: BASE_URL + 'getuserwishes/',
    GetBalance: BASE_URL + 'getaccountbalance',
    GetEmojisWithCategory: BASE_URL + 'emojis',
    CheckAppVersions: BASE_URL + 'check-appversion',
    GetMyReferrals: BASE_URL + 'getreferralreward',
    RedeemReferralRewards: BASE_URL + 'redeemreferralreward',
    TrackUser: BASE_URL + 'trackuser',
    TrackItems: BASE_URL + 'trackitems',
    GetEvents: BASE_URL + 'getevents',
    GetClientSecretStripe: BASE_URL + 'get_customer_fc_session',
    PostClientSecret: BASE_URL + 'add_source_bank',
    GetClientSecretStripeBank: BASE_URL + 'get_stripe_account_fc_session',
    PostClientSecretBank: BASE_URL + 'add_payout_bank',
    BalancePayout: BASE_URL + 'balance_payout',
    CheckProfileDetail: BASE_URL + 'checkuserprofile',
    GetVerificationSession: BASE_URL + 'createverificationsession',
    GetStripStatus: BASE_URL + 'check_user_stripe_acc_status',
    AdminMargin: BASE_URL + 'getadminmargin',
    GetAppVersion: BASE_URL + 'check_app_update',
    UpdateSSN: BASE_URL + 'add_ssn_to_stripe_acc',
    UpdateDoc: BASE_URL + 'add_document_to_stripe_acc',
    ErrorHandler: BASE_URL + 'error_handler',
    AddStripeBankAccount: BASE_URL + 'add_bank_account',
    GetBanners: BASE_URL + 'banners',
    SocialSignup: BASE_URL + 'social_signup',
    CreateDonationProfile: BASE_URL +  "charitable_GFTing/create_profile",
    GetDonationProfile: BASE_URL + "charitable_GFTing/get_profile",
    UpdateDonationProfile: BASE_URL + "charitable_GFTing/update_profile",
    CreateDonationWishlist: BASE_URL + "charitable_GFTing/create_wishlist",
    GetDonationWishlist: BASE_URL + "charitable_GFTing/get_wishlists",
    DeleteDonationWishlist : BASE_URL + "charitable_GFTing/delete_wishlist/",
    UpdateDonationWishlist: BASE_URL + "charitable_GFTing/edit_wishlist/",
    AddDonationItem: BASE_URL + "charitable_GFTing/create_wishlist_item",
    GetDonationItems: BASE_URL + "charitable_GFTing/get_wishlist_items/",
    DeleteDonationitem: BASE_URL + "charitable_GFTing/delete_wishlist_item/",
    UpdateDonationItem : BASE_URL + "charitable_GFTing/edit_wishlist_item/",
    getDonationTransections : BASE_URL + "charitable_GFTing/get_transactions",
    getDonationRoles : BASE_URL + "charitable_GFTing/get_profile_roles"
};

export const Headers = {
    headers: { 
        Accept: 'application/json',
        'Content-Type': 'text/plain',
    },
};
